### ISSUE TITLE
[meta] Inaccurate or failing parses

### ISSUE THREAD

**Issue by jmitchell** [jmitchell/tree-sitter-dhall#2]
Returned parse trees may be inaccurate or include `ERROR` nodes for valid input. Known cases like these are added to [`./corpus-broken`](https://github.com/jmitchell/tree-sitter-dhall/tree/master/corpus-broken) and listed here.

#### Inaccurate
  - expected `reserved_raw`; got `reserved_namespaced_raw`
    - [ ] [Identifier Reserved Namespaced Prefix (List/foldWith)](https://github.com/jmitchell/tree-sitter-dhall/blob/76503e2c4c968c4a5e0016813fda2b38ed701b7e/corpus-broken/primitive-expression.txt#L1-L9)
  - expected `identifier_reserved_namespaced_prefix`; got `identifier_reserved_prefix`
    - [ ] [Identifier Reserved Namespaced Prefix (List/a/b/c/1-2_3@4)](https://github.com/jmitchell/tree-sitter-dhall/blob/76503e2c4c968c4a5e0016813fda2b38ed701b7e/corpus-broken/primitive-expression.txt#L11-L19)

#### Includes `ERROR` nodes
  - [ ] [Record Literal (non-empty)](https://github.com/jmitchell/tree-sitter-dhall/blob/76503e2c4c968c4a5e0016813fda2b38ed701b7e/corpus-broken/primitive-expression.txt#L21-L27)

Fixed tests should be migrated to [`./corpus`](https://github.com/jmitchell/tree-sitter-dhall/tree/master/corpus). I'll also check the corresponding box here and link to the commit/PR with the fix.

## How to help

Open an issue with a link to this issue if you'd like to discuss any particular failing test.

Create a pull request if you'd like to contribute a new failing [tree-sitter unit test](http://tree-sitter.github.io/tree-sitter/creating-parsers#writing-unit-tests) or discovered a fix.
